src/Pat/CompteBundle/Form/AdminProprietaireForm.php
<?php

namespace Pat\CompteBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class AdminProprietaireForm extends AbstractType
{

  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    //parent::buildForm($builder, $options);
    //parent::buildUserForm($builder, $options);
    // Add custom fields
    $builder
      ->add('civilite', 'choice', array(
        'label' => "Civilité",
        'choices' => array(
          'M.' => 'M.',
          'Mlle' => 'Mlle',
          'Mme' => 'Mme',
        ),
        'multiple' => false,
      ))
      ->add('prenom', 'text', array('label' => "Prénom", 'required' => false, 'render_optional_text' => false))
      ->add('nom', 'text', array('label' => "Nom", 'required' => true, 'render_optional_text' => false))
      ->add('societe', 'text', array('label' => "Société", 'required' => false, 'render_optional_text' => false))
      ->add('siret', 'text', array('label' => "Siret", 'required' => false, 'render_optional_text' => false))
      ->add('fonction', 'text', array('label' => "Fonction", 'required' => false, 'render_optional_text' => false))
      ->add('date_naissance', 'birthday', array(
        'widget' => 'choice',
        'years' => range(date('Y') - 18, 1900),
        'format' => 'dd / MM / yyyy',
        'empty_value' => '',
        'required' => false, 'render_optional_text' => false))
      ->add('nationalite', 'text', array('label' => "Nationalité", 'required' => false, 'render_optional_text' => false))
      ->add('langue_parle', 'choice', array(
        'label' => "Langue préférée",
        'choices' => array(
          'Français' => 'Français',
          'Anglais' => 'Anglais',
          'Allemand' => 'Allemand',
          'Espagnol' => 'Espagnol',
          'Italien' => 'Italien',
          'Russe' => 'Russe',
          'Chinois' => 'Chinois',
        ),
        'multiple' => false,
      ))
      ->add('adresse', 'text', array('label' => "Adresse", 'required' => true))
      ->add('adresse2', 'text', array('label' => "Adresse suite", 'required' => false, 'render_optional_text' => false))
      ->add('code_postal', 'text', array('label' => "Code postal", 'required' => true))
      ->add('ville', 'text', array('label' => "Ville", 'required' => true))
      ->add('pays', 'text', array('label' => "Pays", 'required' => true))
      ->add('telephone', 'text', array('label' => "Téléphone", 'required' => false, 'render_optional_text' => false))
      ->add('mobile', 'text', array('label' => "Mobile Mr", 'required' => false, 'render_optional_text' => false))
      ->add('mobile2', 'text', array('label' => "Mobile Mme", 'required' => false, 'render_optional_text' => false))
//            ->add('mails_second', 'textarea', array(
//                    'label' => "Adresses e-mail secondaires",
//                    'required' => false
//                ))
      ->add('second_email', 'text', array(
        'label' => "Adresse e-mail secondaire",
        'required' => false
      ))
      ->add('moyen_contact', 'choice', array(
        'choices' => array(
          'TELEPHONE' => 'Téléphone',
          'MAIL' => 'Mail',
          'SMS' => 'SMS'
        ),
        'multiple' => false,
        'required' => false,
        'render_optional_text' => false,
        "label" => "Moyen de contact préféré"
      ))
      //->add('username', 'text', array('label' => "Identifiant", 'required' => true ))
      ->add('email', 'text', array('label' => "E-mail", 'required' => true))
      ->add('rib_etab', 'text', array("required" => false, 'max_length' => 5, 'label' => "Code Banque"))
      ->add('rib_code', 'text', array("required" => false, 'max_length' => 5, 'label' => "Code Guichet"))
      ->add('rib_compte', 'text', array("required" => false, 'max_length' => 11, 'label' => "Num compte"))
      ->add('rib_rice', 'text', array("required" => false, 'max_length' => 2, 'label' => "Clé RIB"))
      ->add('rib_domiciliation', 'text', array("required" => false, 'max_length' => 100, 'label' => "Domiciliation"))
      ->add('rib_iban', 'text', array("required" => false, 'max_length' => 27, 'label' => "Code IBAN"))
      ->add('rib_bic', 'text', array("required" => false, 'label' => "Code SWIFT (BIC)"))
      ->add('rib_agence_resp', 'text', array("required" => false, 'max_length' => 255, 'label' => "Agence responsable du compte"))
      ->add('rib_pays', 'text', array("required" => false, 'max_length' => 100, 'label' => "Pays"))
      ->add('rib_titulaire', 'text', array("required" => false, 'max_length' => 100, 'label' => "Titulaire"))
    ;
  }

  public function getName()
  {
    return 'proprietaire';
  }

}

src/Pat/CompteBundle/Controller/AdminProprietaireController.php
<?php

namespace Pat\CompteBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\DependencyInjection\ContainerAware,
    Symfony\Component\HttpFoundation\RedirectResponse;
use Pat\CompteBundle\Form\AdminProprietaireRechercheForm;
use Pat\CompteBundle\Form\AdminProprietaireForm;
use Pat\UtilisateurBundle\Entity\Utilisateur;
use Pat\UtilisateurBundle\Repository\UtilisateurRepository;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\Encoder\MessageDigestPasswordEncoder;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\Session\Session;

class AdminProprietaireController extends ContainerAware
{

  //afficher le formulaire d'ajout d'un propriétaire
  public function ajouterAction($id_proprio = null, $message = null, $erreur = null)
  {

    // On stock le referer s'il n'est pas déjà en session
    if (is_null($this->container->get('session')->get('previous_page'))) {
      $url = $this->container->get('request')->headers->get("referer");
      $this->container->get('session')->set('previous_page', $url);
    }

    $this->locale = $this->container->get('request')->getLocale();
    $validation = '';
    $em = $this->container->get('doctrine')->getManager();


    //on récupère l'utilisateur courant
    $user_context = $this->container->get('security.context')->getToken()->getUser();
    $user = $em->find('PatUtilisateurBundle:Utilisateur', $user_context->getId());

    if (!$user) {
      throw new AccessDeniedException('This user does not have access to this section.');
    }

    if (isset($id_proprio)) {
      $utilisateur = $em->getRepository('PatUtilisateurBundle:Utilisateur')->findOneBy(array("type_utilisateur" => "2", "id" => $id_proprio));
      if (!$utilisateur) {
        throw new AccessDeniedException("Cet utilisateur n'existe pas");
      }
    }
    else {
      // ajout d'un nouvel utilisateur
      $utilisateur = new Utilisateur();
    }


    $form = $this->container->get('form.factory')->create(new AdminProprietaireForm(), $utilisateur);
    $request = $this->container->get('request');

    if ($request->getMethod() == 'POST') {

      $form->bind($request);

      if ($form->isValid()) {

        $patternEmail = '#^[\w.-]+@[\w.-]+\.[a-zA-Z]{2,6}$#';

        if (!preg_match($patternEmail, $form['email']->getData())) {
          $message = "L'adresse mail n'est pas valide";
        }
        else {

          //s'il s'agit d'un nouveau proprio
          if (!isset($id_proprio)) {

            $isExistEmail = $em->getRepository('PatUtilisateurBundle:Utilisateur')->checkEmailCompteAction($form['email']->getData());

            if (!$isExistEmail) {
              $utilisateur->setEmailCanonical($form['email']->getData());
              $utilisateur->setConfirmationToken(null);
              $utilisateur->setEnabled(true);
              $utilisateur->setProprietaire();
              $utilisateur->setCGU("1");

              //gestion du mot de passe
              $password = $em->getRepository('PatUtilisateurBundle:Utilisateur')->generatePassword();
              $encoder = $this->container->get('security.encoder_factory')->getEncoder($utilisateur);
              $utilisateur->setPassword($encoder->encodePassword($password, $utilisateur->getSalt()));
              $utilisateur->setConfirmationToken($this->container->get('fos_user.util.token_generator')->generateToken());
              $url = $this->container->get('router')->generate('fos_user_registration_confirm', array(
                'token' => $utilisateur->getConfirmationToken()
              ), true);

              $em->persist($utilisateur);
              $em->flush();

              $utilisateur->generateUsername();

              $em->flush();

              //envoi du mail au proprietaire
              $message_email = \Swift_Message::newInstance()
                ->setSubject("Création de votre compte propriétaire - classAppart ®")
                ->setFrom('contact@class-appart.com')
                ->setBcc($this->container->getParameter('mail_admin'))
                ->setTo($utilisateur->getEmail());

//                            if($utilisateur->getMailsSecond())
//                                $message_email->setCc(explode(',', $utilisateur->getMailsSecond()));
              if ($utilisateur->getSecondEmail()) {
                $message_email->setCc($utilisateur->getSecondEmail());
              }

              $textBody = $this->container->get('templating')->render(
                'PatCompteBundle:AdminProprietaire:email_validation.txt.twig',
                compact('utilisateur', 'password', 'url')
              );
              $htmlBody = $this->container->get('templating')->render(
                'PatCompteBundle:AdminProprietaire:email_validation.html.twig',
                compact('utilisateur', 'password', 'url')
              );

              if (!empty($htmlBody)) {
                $message_email->setBody($htmlBody, 'text/html')
                  ->addPart($textBody, 'text/plain');
              }
              else
                $message_email->setBody($textBody);

              $this->container->get('mailer')->send($message_email);


              $message = 'Propriétaire ajouté avec succès !';
              $this->container->get('session')->getFlashBag()->add('flash', $message);

              //return new RedirectResponse($this->container->get('router')->generate('pat_admin_proprietaire_editer', array('id_proprio' => $utilisateur->getId())));
              return new RedirectResponse($this->container->get('router')->generate('pat_admin_proprietaire_afficher', array('id_proprio' => $utilisateur->getId())));
            }
            else {
              $message = 'Cette adresse mail existe déjà';
            }
          }
          else {  //s'il s'agit d'une modification de compte
            $isExistEmail = $em->getRepository('PatUtilisateurBundle:Utilisateur')->checkEmailCompteAction($form['email']->getData(), $id_proprio);
            if (!$isExistEmail) {
              $utilisateur->setEmailCanonical($form['email']->getData());
              $utilisateur->setUpdatedAt(new \DateTime("now"));

              // gestion du mot de passe
              // $password = $em->getRepository('PatUtilisateurBundle:Utilisateur')->generatePassword();
              // $encoder = $this->container->get('security.encoder_factory')->getEncoder($utilisateur);
              // $utilisateur->setPassword($encoder->encodePassword($password, $utilisateur->getSalt()));

              $em->flush();

              $this->container->get('session')->getFlashBag()->add('success', 'Propriétaire modifié avec succès !');

              // On récupère le referer stocké, le supprime de la session et redirige vers cette page
              $previous_page = $this->container->get('session')->get('previous_page');
              $this->container->get('session')->remove('previous_page');

              if ($previous_page)
                return new RedirectResponse($previous_page);
              else
                return new RedirectResponse($this->container->get('router')->generate('pat_admin_proprietaire_afficher', array('id_proprio' => $utilisateur->getId())));
            }
            else {
              $message = 'Cette adresse mail existe déjà';
            }
          }//end if proprio
        }
      }
    }


    return $this->container->get('templating')->renderResponse(
        'PatCompteBundle:AdminProprietaire:ajouter.html.twig', array(
        'form' => $form->createView(),
        'message' => $message,
        'utilisateur' => $utilisateur,
        'id_proprio' => $id_proprio,
    ));
  }

  public function testTabVide($tab)
  {
    foreach ($tab as $t):
      if ($t != null && $t != "") {
        return false;
      }
    endforeach;
    return true;
  }

  //lister les propriétaire
  public function indexAction($message = null)
  {
    $em = $this->container->get('doctrine')->getManager();

    //on récupère l'utilisateur courant
    $user_context = $this->container->get('security.context')->getToken()->getUser();
    $user = $em->find('PatUtilisateurBundle:Utilisateur', $user_context->getId());

    $session = $this->container->get('request')->getSession();

    $formRecherche = $this->container->get('form.factory')->create(new AdminProprietaireRechercheForm());
    $request = $this->container->get('request');
    $type = "2"; //on recherche un propriétaire
    // Si requête POST, alors c'est une nouvelle recherche, on stock les valeurs en session si le formulaire est valide
    if ($request->getMethod() == 'POST') {

      $formRecherche->bind($request);

      if ($formRecherche->isValid()) {
        $proprietairerecherche = $request->request->get('proprietairerecherche');

        $admin_search_prop = array();
        $admin_search_prop['nom'] = str_replace("'", " ", $proprietairerecherche["nom"]);
        $admin_search_prop['prenom'] = str_replace("'", " ", $proprietairerecherche["prenom"]);
        $admin_search_prop['num_compte'] = str_replace("'", " ", $proprietairerecherche["num_compte"]);

        $session->set('admin_search_prop', $admin_search_prop);
      }
      else {
        $pagination = array();
        //$message = "Veuillez entrer au moins un des critères !";
      }
    }
    else {
      if ($this->container->get('request')->query->get('page')) {
        // On récupère les éléments de recherche en session
        $admin_search_prop = $session->get('admin_search_prop');
      }
      else {
        // Si page n'est pas définie, on souhaite afficher tous les propriétaires

src/Pat/CompteBundle/Resources/views/AdminProprietaire/afficher.html.twig
{% extends 'PatCompteBundle::layout_admin.html.twig' %}
{% block content %}
  {% include "PatCompteBundle:AdminProprietaire:afficher_content.html.twig" %}
{% endblock content %}

src/Pat/CompteBundle/Resources/views/AdminProprietaire/afficher_content.html.twig
{% block content %}

  <div id="contenuCentrale1">
    <h1>Compte propriétaire <small>({{ proprietaire.prenom | capitalize }} {{ proprietaire.nom | upper }})</small></h1>

    <div class="clear"></div>

    <div class="etapesBien">
      <div class="linksEtapesBien">
        <ul>
          <li><a class="active" href="{{ path('pat_admin_proprietaire_afficher', { 'id_proprio': proprietaire.id }) }}">Profil</a></li>
          <li><a href="{{ path('pat_admin_proprietaire_appartement_index', { 'id_proprio': proprietaire.id }) }}">Biens</a></li>
          <li><a href="{{ path('pat_admin_proprietaire_reservation_index', { 'id_proprio': proprietaire.id }) }}">Réservations Propriétaire</a></li>
          <li><a href="{{ path('pat_admin_proprietaire_resas_loc', { 'id_proprio': proprietaire.id }) }}">Réservations Locataire</a></li>
          <li><a href="{{ path('pat_admin_list_payment_by_member', { 'member_id': proprietaire.id }) }}">Paiements</a></li>
          <li><a href="{{ path('documentsAdmin_list',{ 'user_id':proprietaire.id}) }}">Documents</a></li>
        </ul>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span6">
        <a href="{{ path('pat_admin_send_infos_prop', { 'id_proprio': proprietaire.id }) }}" class="btn btn-secondary">Envoyer les informations</a>
      </div>
      <div class="span6 right">
        <div class="btn-group">
          <a class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="#">
            Générer un e-mail de paiement
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="{{ path('pat_admin_generate_payment', { 'member_id': proprietaire.id }) }}">Paiement simple</a></li>
              {% for resa in reservations %}
              <li><a href="{{ path('pat_admin_generate_payment_resa', { 'member_id': proprietaire.id, 'id_reservation': resa.id }) }}">Réservation {{ resa.reference }}</a></li>
              {% endfor %}
          </ul>
        </div>
      </div>
    </div>

    {% if app.session.started %}
      {% for flashMessage in app.session.flashbag.get('error') %}
        <div class="alert alert-error">
          {{ flashMessage }}
        </div>
      {% endfor %}

      {% for flashMessage in app.session.flashbag.get('success') %}
        <div class="alert alert-success">
          {{ flashMessage }}
        </div>
      {% endfor %}
    {% endif %}

    <div class="blocForm">
      <div class="title">
        <div class="row-fluid">
          <div class="span6">
            {{ proprietaire.prenom | capitalize }} {{ proprietaire.nom | upper }}
          </div>
          <div class="span6 right">
            N° {{ proprietaire.username }}
          </div>
        </div>
      </div>

      <div class="content">
        <div class="row-fluid">
          <div class="span4 right">
            Civilité :
          </div>
          <div class="span8">
            {{ proprietaire.civilite }}
          </div>
        </div>

        <div class="row-fluid">
          <div class="span4 right">
            Nom :
          </div>
          <div class="span8">
            {{ proprietaire.nom }}
          </div>
        </div>

        <div class="row-fluid">
          <div class="span4 right">
            Prénom :
          </div>
          <div class="span8">
            {{ proprietaire.prenom }}
          </div>
        </div>

        <div class="row-fluid">
          <div class="span4 right">
            Date de naissance :
          </div>
          <div class="span8">
            {% if proprietaire.dateNaissance %}
              {{ proprietaire.dateNaissance|date("d/m/Y") }}
            {% endif %}
          </div>
        </div>

        <div class="row-fluid">
          <div class="span4 right">
            Nationalité :
          </div>
          <div class="span8">
            {{ proprietaire.nationalite }}
          </div>
        </div>

        <div class="row-fluid">
          <div class="span4 right">
            Langue préférée :
          </div>
          <div class="span8">
            {{ proprietaire.langueParle }}
          </div>
        </div>

        <div class="row-fluid">
          <div class="span4 right">
            Adresse :
          </div>
          <div class="span8">
            {{ proprietaire.adresse }}
          </div>
        </div>

        <div class="row-fluid">
          <div class="span4 right">
            Ville :
          </div>
          <div class="span8">
            {{ proprietaire.ville }}
          </div>
        </div>

        <div class="row-fluid">
          <div class="span4 right">
            Pays :
          </div>
          <div class="span8">
            {{ proprietaire.pays }}
          </div>
        </div>

        <div class="row-fluid">
          <div class="span4 right">
            Téléphone :
          </div>
          <div class="span8">
            {{ proprietaire.telephone }}
          </div>
        </div>

        <div class="row-fluid">
          <div class="span4 right">
            Mobile Mr :
          </div>
          <div class="span8">
            {{ proprietaire.mobile }}
          </div>
        </div>

        {% if proprietaire.mobile2 %}
          <div class="row-fluid">
            <div class="span4 right">
              Mobile Mme :
            </div>
            <div class="span8">
              {{ proprietaire.mobile2 }}
            </div>
          </div>
        {% endif %}

        <div class="row-fluid">
          <div class="span4 right">
            Moyen de contact préféré :
          </div>
          <div class="span8">
            {{ proprietaire.moyenContact|trans }}
          </div>
        </div>

        <div class="row-fluid">
          <div class="span4 right">
            Email :
          </div>
          <div class="span8">
            <a href="mailto:{{ proprietaire.email }}">{{ proprietaire.email }}</a>
          </div>
        </div>

        {#            <div class="row-fluid">
                        <div class="span4 right">
                            Email secondaires :
                        </div>
                        <div class="span8">
                            {{ proprietaire.mailsSecond }}
                        </div>
                    </div>
        #}
        <div class="row-fluid">
          <div class="span4 right">
            Email secondaire :
          </div>
          <div class="span8">
            {{ proprietaire.secondEmail }}
          </div>
        </div>

        <div class="row-fluid">
          <div class="span4 right">
            Identifiant :
          </div>
          <div class="span8">
            {{ proprietaire.username }}
          </div>
        </div>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span2">
        {% if proprietaire.enabled == "1" %}
          <a class="btn" href="{{ path('pat_admin_proprietaire_desactiver', { 'id_proprio': proprietaire.id }) }}" onclick="return confirmAction()">Désactiver</a>
        {% else %}
          <a class="btn" href="{{ path('pat_admin_proprietaire_activer', { 'id_proprio': proprietaire.id }) }}" onclick="return confirmAction()">Activer</a>
        {% endif %}
      </div>

      <div class="span4">
        <a href="{{ path('pat_admin_utilisateur_password', { 'id_user': proprietaire.id }) }}" class="btn btn-primary">Changer mot de passe</a>
      </div>

      <div class="span6 right">
        <a href="{{ path('pat_admin_proprietaire_editer', { 'id_proprio': proprietaire.id }) }}" class="btn btn-large btn-primary pull-right">Modifier</a>
      </div>
    </div>
  </div><!-- /contenuCentrale1 -->

{% endblock %}

src/Pat/CompteBundle/Resources/views/AdminProprietaire/ajouter.html.twig
{% extends 'PatCompteBundle::layout_admin.html.twig' %}
{% block content %}
  {% include "PatCompteBundle:AdminProprietaire:ajouter_content.html.twig" %}
{% endblock content %}

src/Pat/CompteBundle/Resources/views/AdminProprietaire/email_validation.txt.twig
Bonjour,

Votre compte a bien été créé/modifié sur notre site class-appart.com.

Cependant vous devez l'activer en vous rendant sur :

{{url}}

Vous pouvez vous connecter dans la partie Mon compte sur {{ app.request.getSchemeAndHttpHost()~path('fos_user_security_login') }}


Vos informations
----------------------------------------------------------------------------------------------------

    Effectuée le {{ 'now' | date('d/m/Y') }}
    Identifiant : {{ utilisateur.username }}
    Mot de passe : {{ password }}

----------------------------------------------------------------------------------------------------

    Si vous avez besoin d’aide supplémentaire, nous vous invitons à nous contacter sur contact@class-appart.com

    À bientôt sur class-appart.com.

----------------------------------------------------------------------------------------------------

Ce message vous a été envoyé d’une adresse qui ne peut recevoir d’e-mail, merci de ne pas y répondre.

src/Pat/CompteBundle/Resources/views/AdminProprietaire/listPayments.html.twig
{% extends 'PatCompteBundle::layout_admin.html.twig' %}
{% block content %}
  {% include "PatCompteBundle:AdminProprietaire:listPayments_content.html.twig" %}
{% endblock content %}

src/Pat/CompteBundle/Resources/views/AdminProprietaire/listPayments_content.html.twig
{% block content %}

  <div id="contenuCentrale1">
    <h1>Paiements <small>({{ proprietaire.prenom | capitalize }} {{ proprietaire.nom | upper }})</small></h1>

    <div class="clear"></div>

    <div class="etapesBien">
      <div class="linksEtapesBien">
        <ul>
          <li><a href="{{ path('pat_admin_proprietaire_afficher', { 'id_proprio': proprietaire.id }) }}">Profil</a></li>
          <li><a href="{{ path('pat_admin_proprietaire_appartement_index', { 'id_proprio': proprietaire.id }) }}">Biens</a></li>
          <li><a href="{{ path('pat_admin_proprietaire_reservation_index', { 'id_proprio': proprietaire.id }) }}">Réservations Propriétaire</a></li>
          <li><a href="{{ path('pat_admin_proprietaire_resas_loc', { 'id_proprio': proprietaire.id }) }}">Réservations Locataire</a></li>
          <li><a class="active" href="{{ path('pat_admin_list_payment_by_member', { 'member_id': proprietaire.id }) }}">Paiements</a></li>
          <li><a href="{{ path('documentsAdmin_list',{ 'user_id':proprietaire.id}) }}">Documents</a></li>
        </ul>
      </div>
    </div>

    {% for flashMessage in app.session.flashbag.get('success') %}
      <div class="alert alert-success">
        {{ flashMessage }}
      </div>
    {% endfor %}

    {% for flashMessage in app.session.flashbag.get('error') %}
      <div class="alert alert-error">
        {{ flashMessage }}
      </div>
    {% endfor %}

    {{ knp_pagination_render(payments) }}

    {% for payment in payments %}
      <div class="ListeAppart row-fluid">
        <div class="span12">
          <div class="row" style="padding: 10px; border-bottom: 1px solid #C5C5C5;">
            <div class="span9">
              {{ payment.name }}
              {% if payment.reservation %}
                <br/><a href="{{ path('pat_admin_reservation_show', { 'id_reservation': payment.reservation.id }) }}"> (Réservation {{payment.reservation.Reference}})</a>
              {% endif %}
            </div>
            <div class="span3 right">
              {% if payment.modePaiement == "cheque" or payment.modePaiement == "virement" %}
                {% if payment.status == constant('\\Pat\\CompteBundle\\Tools\\PaymentTools::CONSTANT_STATUS_WAIT_RECEIPT') %}
                  <a href="{{ path('pat_admin_valider_payment', { 'payment_id': payment.id }) }}" class="btn">Valider</a>
                {% endif %}
              {% endif %}
              <a href="{{ path('pat_admin_edit_payment', { 'id_payment': payment.id }) }}"><i class="icon-edit"></i></a>
            </div>
          </div>
          <div class="row-fluid">
            <div class="span9">
              <div class="row-fluid">
                <div class="span3 ListeAppart1">
                  Ref. {{ payment.id }}
                </div>
                <div class="span4 ListeAppart1" style="margin-left: 0;">
                  {{ payment.modePaiement | trans }}
                </div>

                <div class="span3 ListeAppart1 center" style="margin-left: 0;">
                  {{ payment.createdAt|date("d/m/Y") }}
                </div>

                <div class="span2 ListeAppart1 center" style="margin-left: 0;">
                  <strong>{{ payment.amount | price_format }}€</strong>
                </div>
              </div>
            </div>

            <div class="span3 ListeAppart2 center" style="margin-left: 0;">
              {% if payment.status == constant('\\Pat\\CompteBundle\\Tools\\PaymentTools::CONSTANT_STATUS_WAIT') %}
                <span class="label label-info">En attente</span>
              {% elseif payment.status == constant('\\Pat\\CompteBundle\\Tools\\PaymentTools::CONSTANT_STATUS_WAIT_RECEIPT') %}
                <span class="label label-warning">En attente de réception</span>
              {% elseif payment.status == constant('\\Pat\\CompteBundle\\Tools\\PaymentTools::CONSTANT_STATUS_PAYED') %}
                <span class="label label-success">Payé</span> le {{ payment.payedAt|date("d/m/Y") }}
              {% elseif payment.status == constant('\\Pat\\CompteBundle\\Tools\\PaymentTools::CONSTANT_STATUS_CANCELED') %}
                <span class="label label-important">Annulé</span>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    {% else %}
      <br/><br/>
      <div class="alert">Il n'y a aucun paiement actuellement.</div>
    {% endfor %}
  </div><!-- /contenuCentrale1 -->

{% endblock %}